Upgrades to latest beam version(2.12.0)
2.5.0 can't run in Java11.
error:org.apache.beam.repackaged.beam_runners_direct_java.com.google.common.util.concurrent.UncheckedExecutionException:
java.lang.UnsupportedOperationException: Cannot define class using
reflection: Could not find sun.misc.Unsafe